# Generated by Django 3.2 on 2022-07-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0003_auto_20220701_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
