# Generated by Django 3.2 on 2022-07-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0005_rename_has_sizes_sweet_measurement_of_sweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweet',
            name='sku',
        ),
    ]
