# Generated by Django 3.2 on 2022-08-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='measurement_of_sweet',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
