# Generated by Django 3.2 on 2022-07-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('usermessage', models.CharField(max_length=1000)),
                ('useremail', models.EmailField(max_length=254)),
            ],
        ),
    ]
